Make _LetExpr immutable.
Storing the let bindings as a dict an later splitting keys and values
expecting them to be in the same order is probably not guaranteed (even in
Python 3.6+ where the dict implementation preserves the order).

Furthermore, since bindings where being used the hash which would be a
TypeError: unhashable type...